### ISSUE TITLE
Index out of range error in Drawer.py

### ISSUE THREAD

**Issue by azmikabiwa** [LineIndent/fletxible#2]
Hi,
Thank you for making this template.
I tried to install it using pypi and then run fletxible-init.
The web page wont show up and I got this error message:

File "/Users/hurricane/Documents/pscripts/core/drawer.py", line 28, in __init__
    primary = self.docs["theme"][1]["primary"]
              ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Is there anyway to fix it?

**Comment by LineIndent** [comment]
Hello! 

The issue comes from the config file - it wasn't updated in the last release.
To fix the problem, make sure your fx_config.yml file has the following info:

```yaml
site-name: "fletxible."

repo-url: "https://github.com/LineIndent/fletxible"
repo-name: "LineIndent/fletxible"

theme:
  - bgcolor: "teal"
  - primary: "teal700"

navigation:
  - Start: "installation.py"
  - About: "about.py"
```

You need to have the theme colors inside - you can change the rest as needed.
Don't forget to run the script.py file when you update the fx_config.yml file.
